name: test-yml
on: 
  push:
  workflow_dispatch:
  
jobs:
  build:
   name: My firt Action
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - uses: ./action-a
       with:
         MY_NAME: Thorsten
